### ISSUE TITLE
CT ERROR: too much recursion

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-electromagnetic-lab#171]
```
faradays-electromagnetic-lab : phet-io-state-fuzz : unbuilt
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/phet-io-wrappers/state/?sim=faradays-electromagnetic-lab&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717035017148%22%2C%22timestamp%22%3A1717035986596%7D
ERROR: too much recursion
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:24:43
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:24:43)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
    at  (Property.ts:45:4)
    at currentScreenName (Sim.ts:1114:6)
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/assert/js/assert.js:27:126)
    at assert (ReadOnlyProperty.ts:249:18)
    at get (ReadOnlyProperty.ts:409:16)
====================
FULL LOG:
[URL] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1717035017148%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dfaradays-electromagnetic-lab%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717035017148%22%2C%22timestamp%22%3A1717035986596%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1717035017148%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dfaradays-electromagnetic-lab%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717035017148%22%2C%22timestamp%22%3A1717035986596%7D
[ATTACHED] 
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/phet-io-wrappers/state/?sim=faradays-electromagnetic-lab&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717035017148%22%2C%22timestamp%22%3A1717035986596%7D
[ATTACHED] 
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/faradays-electromagnetic-lab/faradays-electromagnetic-lab_en.html?brand=phet-io&ea&postMessageOnError&sim=faradays-electromagnetic-lab&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717035017148%22%2C%22timestamp%22%3A1717035986596%7D&frameTitle=source
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/faradays-electromagnetic-lab/faradays-electromagnetic-lab_en.html?brand=phet-io&ea&postMessageOnError&sim=faradays-electromagnetic-lab&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717035017148%22%2C%22timestamp%22%3A1717035986596%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717035017148/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
[CONSOLE] Assertion failed:  accessed value outside of dependency tracking
```

**Comment by pixelzoom** [comment]
Slack#dev-public:

@samreid said:

The assertion message now outputs what screen is active when the error happens. But it looks like the upstream error is accessing a non-dependency somewhere in the evaluation of this derived property:
```
    // Keep the entire panel inside drag bounds.
    const dragBoundsProperty = new DerivedProperty(
      [ visibleBoundsProperty, rightPanelsBoundsProperty, content.boundsProperty ],
      ( visibleBounds, rightPanelsBounds, contentBounds ) => {
        const panelWidth = contentBounds.width + 2 * options.xMargin;
        const panelHeight = contentBounds.height + 2 * options.yMargin;
        return new Bounds2(
          visibleBounds.minX + FELConstants.SCREEN_VIEW_X_MARGIN,
          visibleBounds.minY + FELConstants.SCREEN_VIEW_Y_MARGIN,
          rightPanelsBounds.minX - panelWidth - FELConstants.SCREEN_VIEW_X_MARGIN,
          visibleBounds.maxY - panelHeight - FELConstants.SCREEN_VIEW_Y_MARGIN );
      } );
```

@zepumph said:

Hmm, if it is a change in boundsProperty logic, I wonder if it is related to https://github.com/phetsims/natural-selection/issues/363 (total guess here)

**Comment by zepumph** [comment]
This was fixed by https://github.com/phetsims/joist/commit/ff8657b06963957a9cd45db83fcb83690268c19e.. The underlying assertion for strictAxonDependencies remains.

**Comment by zepumph** [comment]
@jonathanolson @pixelzoom and I discussed the underlying strictAxonDependencies problem, and found a workaround. In general we all hate this feature, and this we should remove it generally, but a bandaid was added above before we can discuss.

**Comment by pixelzoom** [comment]
I'm still curious about what changed that broke this, so I'm going to do a bit more poking around.

`stringTest=dynamic` broke sometime between https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.30 (2024-05-24 12:06) and https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.31 (2024-05-28 18:02).

**Comment by pixelzoom** [comment]
I didn't get anywhere with identifying when `stringTest=dynamic` was broken. 

This is no longer failing in CT, so closing.
