### ISSUE TITLE
CT: accessed value outside of dependency tracking

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#57]
Failing on every CT cycle for faradays-electromagnetic-lab, generator, magnet-and-compass, and magnets-and-electromagnets:

```
faradays-electromagnetic-lab : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1705618171549/faradays-electromagnetic-lab/faradays-electromagnetic-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1705618171549%22%2C%22timestamp%22%3A1705619549358%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: accessed value outside of dependency tracking
Error: Assertion failed: accessed value outside of dependency tracking
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1705618171549/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:235:18)
at get (Multilink.ts:110:68)
at Array.map
at map (Multilink.ts:110:38)
at listener (TinyEmitter.ts:123:8)
at emit (TinyStaticProperty.ts:56:9)
at notifyListeners (Node.ts:1514:30)
at onAccessAttempt (TinyStaticProperty.ts:31:9)
at get (DerivedProperty.ts:55:65)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1705618171549%2Ffaradays-electromagnetic-lab%2Ffaradays-electromagnetic-lab_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1705618171549%22%2C%22timestamp%22%3A1705619549358%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1705618171549%2Ffaradays-electromagnetic-lab%2Ffaradays-electromagnetic-lab_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1705618171549%22%2C%22timestamp%22%3A1705619549358%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1705618171549/faradays-electromagnetic-lab/faradays-electromagnetic-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1705618171549%22%2C%22timestamp%22%3A1705619549358%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 583022
[CONSOLE] Assertion failed: accessed value outside of dependency tracking
[PAGE ERROR] Error: Error: Assertion failed: accessed value outside of dependency tracking
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1705618171549/assert/js/assert.js:28:13)
at Property.get (http://128.138.93.172/continuous-testing/ct-snapshots/1705618171549/chipper/dist/js/axon/js/ReadOnlyProperty.js:167:19)
at http://128.138.93.172/continuous-testing/ct-snapshots/1705618171549/chipper/dist/js/axon/js/Multilink.js:49:68
at Array.map (<anonymous>)
at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1705618171549/chipper/dist/js/axon/js/Multilink.js:49:39)
at TinyStaticProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1705618171549/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at TinyStaticProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1705618171549/chipper/dist/js/axon/js/TinyStaticProperty.js:49:10)
at ElectromagnetPanels.validateBounds (http://128.138.93.172/continuous-testing/ct-snapshots/1705618171549/chipper/dist/js/scenery/js/nodes/Node.js:1333:31)
at TinyStaticProperty.get (http://128.138.93.172/continuous-testing/ct-snapshots/1705618171549/chipper/dist/js/axon/js/TinyStaticProperty.js:26:10)
at http://128.138.93.172/continuous-testing/ct-snapshots/1705618171549/chipper/dist/js/axon/js/DerivedProperty.js:32:64
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 1/18/2024, 3:49:31 PM
```

**Comment by pixelzoom** [comment]
Reproduced locally with http://localhost:8080/faradays-electromagnetic-lab/faradays-electromagnetic-lab_en.html?brand=phet&ea&fuzz&debugger&listenerOrder=random(583022).

The failure is at line 95 of FELScreenView:

```ts
    // Panels top aligned with layoutBounds, right aligned with visible bounds.
    Multilink.multilink( [ this.visibleBoundsProperty, options.panels.boundsProperty ],
      ( visibleBounds, panelsBounds ) => {
        options.panels.right = visibleBounds.right - FELConstants.SCREEN_VIEW_X_MARGIN;
95      options.panels.top = this.layoutBounds.top + FELConstants.SCREEN_VIEW_Y_MARGIN;
      } );
```

I don't understand why this is failing. This is a Multilink, not a DerivedProperty.  So is there something in scenery that is failing when `this.layoutBounds.top` is computed? 

I also don't understand why this is only failing with `listenerOrder=random(583022)`.

I could use some help from @samreid.

**Comment by pixelzoom** [comment]
Making this change does not eliminate the error, so it's not related to `this.layoutBounds`.   It must have something to do with `options.panels.top`, which is an ES5 setter for `setTop( top: number )`.

```diff
    Multilink.multilink( [ this.visibleBoundsProperty, options.panels.boundsProperty ],
      ( visibleBounds, panelsBounds ) => {
        options.panels.right = visibleBounds.right - FELConstants.SCREEN_VIEW_X_MARGIN;
-       options.panels.top = this.layoutBounds.top + FELConstants.SCREEN_VIEW_Y_MARGIN;
+       options.panels.top = FELConstants.SCREEN_VIEW_Y_MARGIN;
      } );
```

**Comment by samreid** [comment]
In my understanding:

```ts
options.panels.top = this.layoutBounds.top + FELConstants.SCREEN_VIEW_Y_MARGIN;
```
causes to set the top of a scenery Node. That causes the Node bounds to revalidate and notify listeners. That causes this derived property to re-evaluate:

```ts
    this.dragBoundsProperty = new DerivedProperty( [ options.panels.boundsProperty ],
      panelsBounds => new Bounds2(
        this.layoutBounds.left,
        this.layoutBounds.top,
        panelsBounds.left,
        this.layoutBounds.bottom
      ) );
```

The problem is that when `this.dragBoundsProperty` tries to take a new value, first it checks whether the new value equals the old value in this code:

```ts
  protected equalsValue( value: T ): boolean {
    return this.areValuesEqual( value, this.get() );
  }
```

It is that call to `get` that makes it think it is querying a non-dependency. This is very related to the "how can a DerivedProperty be OK with querying itself" problem we discussed. I'm not sure how to proceed. It's also unclear why this hasn't happened elsewhere.

**Comment by pixelzoom** [comment]
Because this is happening for all 4 sims on every CT cycle, and I have no way to opt out for a specific DerivedProperty, I'm going to opt out of `strictAxonDependencies` in package.json for all 4 sims until we can figure this out.   Given the amount of work I've put into this issue, this is incredibly disappointing.  Hopefully it's temporary, and I can turn it back on. 

In the meantime, we can test by adding query parameter `strictAxonDependencies=true` to override package.json.

**Comment by pixelzoom** [comment]
This change in FELScreenView seems to work, allowing me to remove `strictAxonDependencies: false` from package.json.

It's troubling that this is needed only for `?listOrderRandom`.

```diff
    this.dragBoundsProperty = new DerivedProperty( [ options.panels.boundsProperty ],
      panelsBounds => new Bounds2(
        this.layoutBounds.left,
        this.layoutBounds.top,
        panelsBounds.left,
        this.layoutBounds.bottom
-      ) );
+      ), {
+        strictAxonDependencies: false //TODO https://github.com/phetsims/faradays-electromagnetic-lab/issues/57
+      } );
```

**Comment by samreid** [comment]
I'm not planning to work on this until I meet up with @pixelzoom. I reached out on slack.

**Comment by pixelzoom** [comment]
The workaround now lives in FELScreenView.ts:

```ts
  protected createDragBoundsProperty( panelsBoundsProperty: TReadOnlyProperty<Bounds2> ): TReadOnlyProperty<Bounds2> {
    return new DerivedProperty( [ panelsBoundsProperty ],
      panelsBounds => this.layoutBounds.withMaxX( panelsBounds.left ), {
        strictAxonDependencies: false //TODO https://github.com/phetsims/faradays-electromagnetic-lab/issues/57
      } );
  }
```

**Comment by samreid** [comment]
Commenting out:

```diff

Subject: [PATCH] Opt out of dependency checking in Helper.ts, see https://github.com/phetsims/scenery/issues/1600
---
Index: js/common/view/FELScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/FELScreenView.ts b/js/common/view/FELScreenView.ts
--- a/js/common/view/FELScreenView.ts	(revision a7850c02d877231b35e044ea363fb5198d56bed8)
+++ b/js/common/view/FELScreenView.ts	(date 1706138319329)
@@ -117,7 +117,7 @@
   protected createDragBoundsProperty( panelsBoundsProperty: TReadOnlyProperty<Bounds2> ): TReadOnlyProperty<Bounds2> {
     return new DerivedProperty( [ panelsBoundsProperty ],
       panelsBounds => this.layoutBounds.withMaxX( panelsBounds.left ), {
-        strictAxonDependencies: false //TODO https://github.com/phetsims/faradays-electromagnetic-lab/issues/57
+        // strictAxonDependencies: false //TODO https://github.com/phetsims/faradays-electromagnetic-lab/issues/57
       } );
   }
 

```

And fuzzing with the random seed specified in http://localhost:8080/faradays-electromagnetic-lab/faradays-electromagnetic-lab_en.html?brand=phet&ea&fuzz&debugger&listenerOrder=random(583022), I am no longer getting any errors.

I do not believe it is fruitful to check strictAxonDependencies when there is a non-default listener order, @pixelzoom OK to  disable the strictness check when an alternate listener order is specified?

```diff

Subject: [PATCH] Opt out of dependency checking in Helper.ts, see https://github.com/phetsims/scenery/issues/1600
---
Index: js/ReadOnlyProperty.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/ReadOnlyProperty.ts b/js/ReadOnlyProperty.ts
--- a/js/ReadOnlyProperty.ts	(revision af410e2df8ff86e0bef50f72b6e59210ecd042bf)
+++ b/js/ReadOnlyProperty.ts	(date 1706138670804)
@@ -77,7 +77,9 @@
   phetioDependencies?: Array<TReadOnlyProperty<unknown>>;
 };
 
-const strictAxonDependencies = _.hasIn( window, 'phet.chipper.queryParameters' ) && phet.chipper.queryParameters.strictAxonDependencies;
+const strictAxonDependencies = _.hasIn( window, 'phet.chipper.queryParameters' ) &&
+                               phet.chipper.queryParameters.strictAxonDependencies &&
+                               phet.chipper.queryParameters.listenerOrder === 'default';
 export const derivationStack: Array<IntentionalAny> = [];
 
 /**

```

**Comment by pixelzoom** [comment]
@samreid and I worked on this. In the above commits are summarized by this PSA to Slack#developer:

> PSA:  Because we have been hitting odd strictAxonDependencies failures when running with ?listenerOrder=random, strictAxonDependencies is now turned off if you change listener order. From ReadOnlyProperty.ts:
```ts
// When changing the listener order via ?listenerOrder, we were running into strictAxonDependencies failures that
// did not otherwise occur. Because we aren't interested in these corner cases, and because they are difficult to
// understand and debug, we chose to turn off strictAxonDependencies if listener order is changed.
// See https://github.com/phetsims/faradays-electromagnetic-lab/issues/57#issuecomment-1909089735
```
