### ISSUE TITLE
CT: mismatched index, possible start/end mismatch

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#65]
This CT error started occurring on every cycle.  It occurs in all sims derived from faradays-electromagnetic-lab (generator, magnet-and-compass, magnets-and-electromagnets) but not in faradays-electromagnetic-lab. It started in these sims 1/26/2024 3:29PM. 

I also see it occurring in keplers-laws, density, and buoyancy, where it started 2 days earlier (??): 1/24/2024 4:46PM.

It occurs immediately on startup from phetmarks with http://localhost:8080/phet-io-wrappers/state/?sim=generator&locales=*&setStateRate=1000&phetioDebug=true&phetioWrapperDebug=true&fuzz

I have no idea what "mismatched index, possible start/end mismatch" means, or how to troubleshoot. Requesting help from @zepumph @samreid.

```
generator : phet-io-state-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/phet-io-wrappers/state/?sim=generator&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22generator%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706372584125%22%2C%22timestamp%22%3A1706373500784%7D
Uncaught Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/assert/js/assert.js:28:13)
at assert (dataStream.ts:299:14)
at end (PhetioObject.ts:512:29)
at phetioEndEvent (phetioCommandProcessor.ts:254:17)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1706372584125%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dgenerator%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22generator%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706372584125%22%2C%22timestamp%22%3A1706373500784%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1706372584125%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dgenerator%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22generator%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706372584125%22%2C%22timestamp%22%3A1706373500784%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/phet-io-wrappers/state/?sim=generator&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22generator%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706372584125%22%2C%22timestamp%22%3A1706373500784%7D
[ATTACHED]
[NAVIGATED] about:blank
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/generator/generator_en.html?brand=phet-io&ea&postMessageOnError&sim=generator&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22generator%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706372584125%22%2C%22timestamp%22%3A1706373500784%7D&frameTitle=source
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/generator/generator_en.html?brand=phet-io&ea&postMessageOnError&sim=generator&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22generator%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706372584125%22%2C%22timestamp%22%3A1706373500784%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: accessed value outside of dependency tracking
[CONSOLE] Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
[PAGE ERROR] Error: Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/assert/js/assert.js:28:13)
at DataStream.end (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/phet-io/js/dataStream.js:253:15)
at PhetioCommandProcessor.phetioEndEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/tandem/js/PhetioObject.js:437:30)
at http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:135:18
[PAGE ERROR] Error: Error: Assertion failed: accessed value outside of dependency tracking
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/assert/js/assert.js:28:13)
at NumberProperty.get (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/axon/js/ReadOnlyProperty.js:171:19)
at get value (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/axon/js/ReadOnlyProperty.js:309:17)
at get value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/axon/js/Property.js:39:18)
at http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/scenery-phet/js/NumberDisplay.js:184:36
at ManualConstraint.layout (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/scenery/js/layout/constraints/ManualConstraint.js:65:27)
at ManualConstraint.updateLayout (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:188:14)
at ManualConstraint.updateLayoutAutomatically (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:201:12)
at TinyStaticProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at TinyStaticProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/axon/js/TinyStaticProperty.js:49:10)
[PAGE ERROR] Error: Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/assert/js/assert.js:28:13)
at DataStream.end (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/phet-io/js/dataStream.js:253:15)
at PhetioCommandProcessor.phetioEndEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/tandem/js/PhetioObject.js:437:30)
at http://128.138.93.172/continuous-testing/ct-snapshots/1706372584125/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:135:18
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 1/27/2024, 9:23:04 AM
```

**Comment by zepumph** [comment]
The assertion says:

`Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.`


When you look at the above log the assertion right above that error is:

`[CONSOLE] Assertion failed: accessed value outside of dependency tracking`. Maybe something in common code axon dependencies changed?

**Comment by samreid** [comment]
I was able to reproduce this problem in my local testing. I saw the assertion error said:

> Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.

So I tried pausing on caught exceptions, and I saw this error:

> Assertion failed:  accessed value outside of dependency tracking

I used the stack trace to identify the derivation that was causing the failure, and tested this patch:

<details>

```diff

Subject: [PATCH] Disable the forward/back buttons on the sample selector when continuous launching, see https://github.com/phetsims/projectile-data-lab/issues/37
---
Index: js/common/view/FELScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/FELScreenView.ts b/js/common/view/FELScreenView.ts
--- a/js/common/view/FELScreenView.ts	(revision 7bf8d695370009b72ba9faddf2f9e7062125d7fa)
+++ b/js/common/view/FELScreenView.ts	(date 1706547374086)
@@ -66,7 +66,9 @@
     this.compassNode = new CompassNode( options.compass, {
       // See https://github.com/phetsims/faradays-electromagnetic-lab/issues/10#issuecomment-1911160748
       dragBoundsProperty: new DerivedProperty( [ this.visibleBoundsProperty, options.panels.boundsProperty ],
-        ( visibleBounds, panelsBounds ) => visibleBounds.withMaxX( panelsBounds.left ) ),
+        ( visibleBounds, panelsBounds ) => visibleBounds.withMaxX( panelsBounds.left ), {
+          strictAxonDependencies: false
+        } ),
       tandem: options.tandem.createTandem( 'compassNode' )
     } );
 

```

</details>

After fuzzing for a while, this patch is not showing any trouble.  Back to you @pixelzoom

**Comment by pixelzoom** [comment]
Thanks @samreid.

But a few questions:
1. What does “mismatched index, possible start/end mismatch” means? 
2. Why does adding `strictAxonDependencies: false` fix this? 
3. Why does this manifest in test “phet-io-state-fuzz” but not in other fuzz tests?

This also needs to be addressed in keplers-laws, density, and buoyancy, as noted in the first comment in this issue.

**Comment by samreid** [comment]
> What does “mismatched index, possible start/end mismatch” means?

Internal consistency check for the data stream. Context is https://github.com/phetsims/phet-io/blob/c93ac0d598abe5e38cb4b6371216cd3a025abe02/js/dataStream.ts#L290-L305

> Why does adding strictAxonDependencies: false fix this?

The stack trace shows that the strictness check cascades to the mismatched index problem.

> Why does this manifest in test “phet-io-state-fuzz” but not in other fuzz tests?

I'm not sure

Here's a patch that identifies the buggy derived property in kepler's laws:

<details>

```diff

Subject: [PATCH] Disable the forward/back buttons on the sample selector when continuous launching, see https://github.com/phetsims/projectile-data-lab/issues/37
---
Index: js/common/view/PeriodTimerNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/PeriodTimerNode.ts b/js/common/view/PeriodTimerNode.ts
--- a/js/common/view/PeriodTimerNode.ts	(revision c7e19c9b7e319b6054c342ab4ddc3c74a7060c4b)
+++ b/js/common/view/PeriodTimerNode.ts	(date 1706548259856)
@@ -217,6 +217,8 @@
 
     const derivedDragBoundsProperty = new DerivedProperty( [ options.dragBoundsProperty, this.localBoundsProperty ], ( dragBounds, localBounds ) => {
       return dragBounds?.withOffsets( localBounds.left, localBounds.top, -localBounds.right, -localBounds.bottom );
+    }, {
+      strictAxonDependencies: false
     } );
 
     const dragListener = new DragListener( {

```

</details>

**Comment by samreid** [comment]
Here's a patch that identifies the derived properties in density that query outside the dependencies:

<details>

```diff

Subject: [PATCH] Disable the forward/back buttons on the sample selector when continuous launching, see https://github.com/phetsims/projectile-data-lab/issues/37
---
Index: js/density/view/DensityIntroScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/density/view/DensityIntroScreenView.ts b/js/density/view/DensityIntroScreenView.ts
--- a/js/density/view/DensityIntroScreenView.ts	(revision 8453854649f2411c11c71ef934e38abfd72870b3)
+++ b/js/density/view/DensityIntroScreenView.ts	(date 1706548475385)
@@ -93,6 +93,8 @@
     this.rightBarrierViewPointProperty.value = new DerivedProperty( [ this.rightBox.boundsProperty, this.visibleBoundsProperty ], ( boxBounds, visibleBounds ) => {
       // We might not have a box, see https://github.com/phetsims/density/issues/110
       return new Vector2( isFinite( boxBounds.left ) ? boxBounds.left : visibleBounds.right, visibleBounds.centerY );
+    }, {
+      strictAxonDependencies: false
     } );
 
     this.addSecondMassControl( model.modeProperty );
Index: js/common/view/DensityBuoyancyScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/DensityBuoyancyScreenView.ts b/js/common/view/DensityBuoyancyScreenView.ts
--- a/js/common/view/DensityBuoyancyScreenView.ts	(revision 8453854649f2411c11c71ef934e38abfd72870b3)
+++ b/js/common/view/DensityBuoyancyScreenView.ts	(date 1706548389181)
@@ -740,7 +740,9 @@
       tandem: Tandem.OPT_OUT
     } );
     // DerivedProperty doesn't need disposal, since everything here lives for the lifetime of the simulation
-    this.rightBarrierViewPointProperty = new Property<TReadOnlyProperty<Vector2>>( new DerivedProperty( [ this.visibleBoundsProperty ], visibleBounds => visibleBounds.rightCenter ), {
+    this.rightBarrierViewPointProperty = new Property<TReadOnlyProperty<Vector2>>( new DerivedProperty( [ this.visibleBoundsProperty ], visibleBounds => visibleBounds.rightCenter, {
+      strictAxonDependencies: false
+    } ), {
       tandem: Tandem.OPT_OUT
     } );
 

```

</details>

**Comment by pixelzoom** [comment]
The patch for FEL is related is the same problem that was encountered in https://github.com/phetsims/faradays-electromagnetic-lab/issues/57.  The problem dependency is visibleBoundsProperty, and we thought the problem was specific to `listenerOrder`.  Maybe there's an order problem with PhET-iO state too? 
 
Looking at the above density patch, the problem is also related to `visibleBoundsProperty`.  Should we do something to address `visibleBoundsProperty`?  Maybe consult with @jonathanolson?

**Comment by samreid** [comment]
One failure case for FEL is in this code:

```ts
    this.compassNode = new CompassNode( options.compass, {
      // See https://github.com/phetsims/faradays-electromagnetic-lab/issues/10#issuecomment-1911160748
      dragBoundsProperty: new DerivedProperty( [ this.visibleBoundsProperty, options.panels.boundsProperty ],
        ( visibleBounds, panelsBounds ) => visibleBounds.withMaxX( panelsBounds.left ) ),
      tandem: options.tandem.createTandem( 'compassNode' )
    } );
```

The panelBounds.left is a TinyStaticProperty.  Calling `get` on it in the derivation causes bounds to revalidate which queries a descendant stroke property to be queried.  That is, the descendant's stroke affects the panelBounds.left value, which affects the derivation.

Likewise, the magnet.strengthPercentProperty is being queried in a descendent NumberDisplay ManualConstraint.  So it looks like adding these values to the dependencies helps: `options.magnet.strengthPercentProperty, ..._.values( FELColors )`.  This gets fuzzing to last a lot longer, but I am still seeing other errors later on, such as:

```ts
assert.js:28 Uncaught Error: Assertion failed: accessed value outside of dependency tracking
    at window.assertions.assertFunction (assert.js:28:13)
    at NumberProperty.get (ReadOnlyProperty.ts:241:19)
    at get value (ReadOnlyProperty.ts:391:17)
    at get value (Property.ts:45:18)
    at NumberDisplay.ts:282:38
    at ManualConstraint.layout (ManualConstraint.ts:81:27)
    at ManualConstraint.updateLayout (LayoutConstraint.ts:201:14)
    at ManualConstraint.updateLayoutAutomatically (LayoutConstraint.ts:215:12)
    at TinyStaticProperty.emit (TinyEmitter.ts:123:9)
    at TinyStaticProperty.notifyListeners (TinyStaticProperty.ts:56:10)
```

So maybe this list is incomplete.  Always investigating all possible transitive dependencies of a DerivedProperty does not seem like a good use of time, I would recommend opting out of the strictness check in this case. Self unassigning.

**Comment by samreid** [comment]
@AgustinVallejo asked me to commit the opt-out-of-strictness check for Kepler's Law, so I did that in https://github.com/phetsims/keplers-laws/issues/247.  @zepumph wanted to have a deeper understanding of where this problem occurs, so I will leave https://github.com/phetsims/density/issues/189 open and @zepumph can reach out for collaboration as desired. I'll leave this issue for @pixelzoom to address as he deems fit.

**Comment by pixelzoom** [comment]
I think I understand why the patch in https://github.com/phetsims/faradays-electromagnetic-lab/issues/65#issuecomment-1915171223 is effective, so I applied it.  Closing.
